version: "{build} ({branch})"

shallow_clone: false
skip_tags: true
clone_folder: C:\unity

environment:

  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - cd C:\unity
  - mvn clean verify

cache:
- C:\Users\appveyor\.m2\repository -> pom.xml