/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext */

#ifndef _Included_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
#define _Included_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
 * Method:    construct
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext_construct
  (JNIEnv *, jobject);

/*
 * Class:     io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext_destroy
  (JNIEnv *, jobject);

/*
 * Class:     io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
 * Method:    register
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext_register
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
 * Method:    setJSONiqVersion
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext_setJSONiqVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext
 * Method:    setXQueryVersion
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_dgms_unity_modules_engines_zorba_ZorbaDGScriptContext_setXQueryVersion
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
