/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unity_modules_engines_zorba_ZorbaDXScriptContext */

#ifndef _Included_unity_modules_engines_zorba_ZorbaDXScriptContext
#define _Included_unity_modules_engines_zorba_ZorbaDXScriptContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unity_modules_engines_zorba_ZorbaDXScriptContext
 * Method:    construct
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_unity_modules_engines_zorba_ZorbaDXScriptContext_construct
  (JNIEnv *, jobject);

/*
 * Class:     unity_modules_engines_zorba_ZorbaDXScriptContext
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_unity_modules_engines_zorba_ZorbaDXScriptContext_destroy
  (JNIEnv *, jobject);

/*
 * Class:     unity_modules_engines_zorba_ZorbaDXScriptContext
 * Method:    register
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_unity_modules_engines_zorba_ZorbaDXScriptContext_register
  (JNIEnv *, jobject, jstring);

/*
 * Class:     unity_modules_engines_zorba_ZorbaDXScriptContext
 * Method:    setJSONiqVersion
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_unity_modules_engines_zorba_ZorbaDXScriptContext_setJSONiqVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     unity_modules_engines_zorba_ZorbaDXScriptContext
 * Method:    setXQueryVersion
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_unity_modules_engines_zorba_ZorbaDXScriptContext_setXQueryVersion
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
